version: '3'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8765:8765"
    environment:
      BOOK_SERVICE_URL: http://book-service:8080
      AUTH_SERVICE_URL: http://auth-service:8082

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  book-service:
    container_name: book-service
    build:
      context: ./book-service
    ports:
      - "8080:8080"
    depends_on:
      - book-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book-postgres:5432/books
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      LIBRARY_SERVICE_URL: http://library-service:8081/library

  library-service:
    container_name: library-service
    build:
      context: ./library-service
    ports:
      - "8081:8081"
    depends_on:
      - library-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://library-postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  book-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  library-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"