server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: http://localhost:8080/
          predicates:
            - Path=/books/**

        - id: auth-service
          uri: http://localhost:8082/
          predicates:
            - Path=/auth/**